-- CreateTable
CREATE TABLE "ContractReview" (
    "id" TEXT NOT NULL,
    "contractNo" TEXT NOT NULL,
    "itemCode" TEXT NOT NULL,
    "mcNo" TEXT,
    "itemName" TEXT,
    "partyItemName" TEXT,
    "rate" TEXT,
    "cv" TEXT,
    "vaPercent" TEXT,
    "orderQty" TEXT,
    "freeStock" TEXT,
    "finalReq" TEXT,
    "mcQty" TEXT,
    "balanceMc" TEXT,
    "prodOrdQty" TEXT,
    "balanceToProdOrd" TEXT,
    "balanceToProdEnt" TEXT,
    "diQty" TEXT,
    "billedQty" TEXT,
    "balBillAgMc" TEXT,
    "balBillAgCont" TEXT,
    "item" TEXT,
    "value" TEXT,
    "size" TEXT,
    "pnRating" TEXT,
    "dateOfContract" TEXT,
    "clearanceStatus" TEXT,
    "actuator" TEXT,
    "rmCodeForActuator" TEXT,
    "rmCodeForGb" TEXT,
    "paymentTerms" TEXT,
    "lcRtgsRefNo" TEXT,
    "lcDateRtgsDate" TEXT,
    "lastDateOfShipmentDateOfLc" TEXT,
    "issuingBankName" TEXT,
    "bomFormulaTrial" TEXT,
    "erpPartyNameFromGmdSupplyHistory" TEXT,
    "itemType" TEXT,
    "jobCode" TEXT,
    "balDiQty" TEXT,
    "balMcVal" TEXT,
    "balProdOrdVal" TEXT,
    "balToProdOrdEntVal" TEXT,
    "balBillAgMcVal" TEXT,
    "balBillAgContVal" TEXT,
    "balDiVal" TEXT,
    "state" TEXT,
    "utility" TEXT,
    "projectReference" TEXT,
    "diVal" TEXT,
    "icQty" TEXT,
    "bomId" TEXT,
    "noUse" TEXT,
    "partyNameDump" TEXT,
    "status" TEXT,
    "mcReceivedPending" TEXT,
    "inspection" TEXT,
    "offerPendingDone" TEXT,
    "remarks" TEXT,
    "offerNumber" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "inspectionNumber" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "diDate" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "costfromQuotation" TEXT,
    "vaPercentfromcost" TEXT,
    "productionOrderNumber" TEXT,
    "diagramUrl" TEXT,
    "diagramVerdict" TEXT,
    "poNo" TEXT,
    "orderList" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "syncedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ContractReview_pkey" PRIMARY KEY ("id")
);
